### Add a new Book
POST http://localhost:5173/api/books
Content-Type: application/json

{
  "title": "Kabel",
  "author": "sam",
  "price": 50
}

### Get All Books
GET http://localhost:5173/api/books

### Get a Book by ID
GET http://localhost:5173/api/books/1